site_name: GrowMate
repo_url: "https://github.com/Sensing-My-Home/Documentation/"
edit_url: "https://github.com/Sensing-My-Home/"

theme:
  name: null
  custom_dir: growmate
  colorscheme: github
  highlightjs: true

nav:
  - Home: index.md

markdown_extensions:
  - admonition
  - toc:
      permalink: true
